app:
  name: currency
  port: 8080
mongodb:
  urls:
    - ip-10-1-2-126.ap-southeast-1.compute.internal
  port: 27017
  database: currency
  replica_set:
  username: admin
  password: PS5blUAMwkB34ZZo
webservices:
  fixer:
    url: http://data.fixer.io/api
    api_key: cda0d18a191f78eb3ec4302b2bedbe39